### ISSUE TITLE
Button hover modifies whole component width

### ISSUE THREAD

**Issue by OscarCasadoLorenzo** [OscarCasadoLorenzo/REACTLab#1]
**Issue related to the project [00-twitter-card](https://github.com/OscarCasadoLorenzo/REACTLab/tree/master/00-twitter-card)**

As we can see on the video when we hover on the button while we are following someone appears the 'Unfollow' text (which is slightly smaller) and it produces a width variation in the whole component that breaks it.

**Evidence:**
https://github.com/OscarCasadoLorenzo/REACTLab/assets/108931971/b5d4da9b-e6c0-4125-9a18-6cc21ae1058e

I'm sure there must be a flexbox attribute that blocks the width reserved for the button so that even if the button is modified it doesn't affect the rest of the component but I don't know how to do it.

**Related code:**
[TwitterFollowCard.jsx](https://github.com/OscarCasadoLorenzo/REACTLab/blob/master/00-twitter-card/src/TwitterFollowCard.jsx)
[App.css](https://github.com/OscarCasadoLorenzo/REACTLab/blob/master/00-twitter-card/src/App.css)

**Comment by pedro-moran228** [comment]
This happens because each element of the list has two boxes, one for the detail and another for the button.

Since the button box size is changeable (by the hover), it needs a static width (referring to the longest button format that can appear).

An easy way to fix this would be using grid css.

![Screenshot from 2023-07-29 23-40-42](https://github.com/OscarCasadoLorenzo/REACTLab/assets/67437652/e07b8165-b008-409e-8505-d83578fab093)
![Screenshot from 2023-07-29 23-39-48](https://github.com/OscarCasadoLorenzo/REACTLab/assets/67437652/5876f595-d2ed-48da-a775-88696c38c307)


It's important that you use **column-gap** instead of **margin-left** for the button because otherwise it will generate the following bug.

![image](https://github.com/OscarCasadoLorenzo/REACTLab/assets/67437652/ce99742b-fdf8-4988-9003-3d14b6d7af2a)

**Comment by Aryan9592** [comment]
Or just make this change to your App.css file under `.suggestUser`

```
.suggestUser{
    width: 284px;
    ...rest of the code
}
```

**Comment by OscarCasadoLorenzo** [comment]
> This happens because each element of the list has two boxes, one for the detail and another for the button.
> 
> Since the button box size is changeable (by the hover), it needs a static width (referring to the longest button format that can appear).
> 
> An easy way to fix this would be using grid css.
> 
> ![Screenshot from 2023-07-29 23-40-42](https://user-images.githubusercontent.com/67437652/257024122-e07b8165-b008-409e-8505-d83578fab093.png) ![Screenshot from 2023-07-29 23-39-48](https://user-images.githubusercontent.com/67437652/257025713-5876f595-d2ed-48da-a775-88696c38c307.png)
> 
> It's important that you use **column-gap** instead of **margin-left** for the button because otherwise it will generate the following bug.
> 
> ![image](https://user-images.githubusercontent.com/67437652/257026094-ce99742b-fdf8-4988-9003-3d14b6d7af2a.png)

It is probably a way to solve the problem but I would like to align buttons to the right of the container.

**Comment by OscarCasadoLorenzo** [comment]
> Or just make this change to your App.css file under `.suggestUser`
> 
> ```
> .suggestUser{
>     width: 284px;
>     ...rest of the code
> }
> ```

It works perfectly, I thought about this answer but I expected not to have to use static values at all. Anyways it has solved the problem so thanks for the contribution.
